language: php
php:
  - '7.0'
  - '7.1'

addons:
  code_climate:
    repo_token: 

install:
  - composer install

script:
  - ./vendor/bin/phpunit --verbose $PHPUNIT_FLAGS

after_success:
  - ./vendor/bin/test-reporter